Repository commown/commown-odoo-addons, pull requests merged in 2022-07, with the labels that each got.

#84 trivial changes
  commown/__manifest__.py
Labels: bot is merging ⏳

#86 12.0 fix product rental cannot manually change contract start date
  commown/models/crm_lead.py
  commown_self_troubleshooting/tests/test_res_partner.py
  product_rental/models/contract.py
  product_rental/tests/test_contract.py
Labels: needs review

#87 [DOC] commown_self_troubleshooting : try to fix documentation
  commown_self_troubleshooting/README.rst
  commown_self_troubleshooting/readme/CONFIGURE.rst
  commown_self_troubleshooting/readme/CONTRIBUTORS.rst
  commown_self_troubleshooting/readme/DESCRIPTION.rst
  commown_self_troubleshooting/readme/USAGE.rst
Labels: bot is merging ⏳

#88 Show the contract template line on contract line form
  contract_variable_discount/views/contract.xml
Labels: bot is merging ⏳, needs review

#89 Improve display of contract infos on order followup page (incl. when not started)
  commown/views/website_sale_templates.xml
Labels: bot is merging ⏳, needs review
