Repository commown/commown-odoo-addons, pull requests merged in 2023-03, with the labels that each got.

#155 Re-fix the crash when generating the last invoice of an auto-pay contract
  commown/models/contract.py
  commown/tests/test_contract.py
Labels: bot is merging ⏳, needs review

#162 Remove twitter from footer
  commown/views/website_templates.xml
  contract_auto_merge_invoice/models/contract.py
  contract_auto_merge_invoice/tests/test_contract.py
  contract_variable_discount/models/discount.py
Labels: needs review

#163 Try to group bought product and their options in the same contract
  product_rental/models/sale_order.py
  product_rental/tests/common.py
  product_rental/tests/test_sale_order.py
  product_rental/tests/test_website.py
Labels: needs review

#164 12.0 fix website sale b2b crash when adding contract line
  rental_fees/__manifest__.py
  rental_fees/models/rental_fees_computation.py
  rental_fees/models/rental_fees_definition.py
  rental_fees/tests/common.py
  rental_fees/tests/test_rental_fees_computation.py
  rental_fees/views/rental_fees_definition.xml
  website_sale_b2b/models/product_pricelist.py
Labels: bot is merging ⏳, needs review

#165 12.0 fix website sale b2b pricelist crash when anonymous
  website_sale_b2b/models/product_pricelist.py
Labels: bot is merging ⏳, needs review

#158 Automatically unsubscribe users from mail_channel when leaving group
  commown/__manifest__.py
  commown/models/__init__.py
  commown/models/res_user.py
  commown/models/res_users.py
  commown/tests/__init__.py
  commown/tests/test_res_users.py
Labels: bot is merging ⏳

#159 12.0 add payment token uniquify
  commown/__manifest__.py
  commown/data/obsolescence_action.xml
  commown/models/__init__.py
  commown/models/payment_token_obsolescence_action.py
  commown/tests/__init__.py
  commown/tests/test_payment_token.py
  payment_token_uniquify/README.rst
  payment_token_uniquify/__init__.py
  payment_token_uniquify/__manifest__.py
  payment_token_uniquify/data/obsolescence_action.xml
  payment_token_uniquify/models/__init__.py
  payment_token_uniquify/models/obsolescence_action.py
  payment_token_uniquify/models/payment_acquirer.py
  payment_token_uniquify/models/payment_token.py
  payment_token_uniquify/models/res_partner.py
  payment_token_uniquify/readme/CONFIGURE.rst
  payment_token_uniquify/readme/CONTRIBUTORS.rst
  payment_token_uniquify/readme/DESCRIPTION.rst
  payment_token_uniquify/readme/USAGE.rst
  payment_token_uniquify/readme/newsfragments/.gitkeep
  payment_token_uniquify/security/ir.model.access.csv
  payment_token_uniquify/static/description/index.html
  payment_token_uniquify/tests/__init__.py
  payment_token_uniquify/tests/common.py
  payment_token_uniquify/tests/test_payment_token.py
  payment_token_uniquify/tests/test_res_partner.py
  payment_token_uniquify/views/payment_acquirer.xml
  payment_token_uniquify/views/res_partner.xml
  setup/payment_token_uniquify/odoo/addons/payment_token_uniquify
  setup/payment_token_uniquify/setup.py
Labels: bot is merging ⏳, needs review

#169 Do not touch partner payment prefs on token signature when already set
  commown/models/payment_token_obsolescence_action.py
  commown/tests/test_payment_token.py
Labels: bot is merging ⏳, needs review

#170 Remove checks disallowing fields fees def modification when computations exist
  rental_fees/models/rental_fees_definition.py
  rental_fees/tests/test_rental_fees_computation.py
Labels: bot is merging ⏳, needs review
