Repository commown/commown-odoo-addons, pull requests merged in 2023-11, with the labels that each got.

#221 Fix taxes not computed after rental computation invoicing
  rental_fees/models/rental_fees_computation.py
  rental_fees/tests/test_rental_fees_computation.py
Labels: bot is merging ⏳, needs review

#222 12.0 imp payment slimpay issue dont ignore merged invoices
  commown_payment_slimpay_issue/__init__.py
  commown_payment_slimpay_issue/models/__init__.py
  commown_payment_slimpay_issue/models/project_task.py
  commown_payment_slimpay_issue/tests/test_project_task.py
  payment_slimpay_issue/models/project_task.py
Labels: needs review

#225 Fix a crash when creating a contract-line specific discount
  contract_variable_discount/views/contract.xml
  contract_variable_discount/views/discount.xml
Labels: needs review

#210 12.0 imp commown integrate contract forecast
  commown/__manifest__.py
  commown_contract_forecast/README.rst
  commown_contract_forecast/__init__.py
  commown_contract_forecast/__manifest__.py
  commown_contract_forecast/data/cron.xml
  commown_contract_forecast/models/__init__.py
  commown_contract_forecast/models/contract.py
  commown_contract_forecast/models/contract_line.py
  commown_contract_forecast/models/contract_line_forecast_period.py
  commown_contract_forecast/models/contract_template_line.py
  commown_contract_forecast/readme/CONFIGURE.rst
  commown_contract_forecast/readme/CONTRIBUTORS.rst
  commown_contract_forecast/readme/CREDITS.rst
  commown_contract_forecast/readme/DESCRIPTION.rst
  commown_contract_forecast/tests/__init__.py
  commown_contract_forecast/tests/test_contract_line.py
  commown_contract_forecast/tests/test_functional.py
  commown_cooperative_campaign/models/discount.py
  commown_cooperative_campaign/tests/test_discount.py
  commown_shipping/tests/test_crm_lead.py
  contract_variable_discount/__manifest__.py
  contract_variable_discount/data/report.xml
  contract_variable_discount/data/report_simulate_payments.xml
  contract_variable_discount/models/contract.py
  contract_variable_discount/tests/test_contract.py
  product_rental/models/payment_transaction.py
  rental_fees/__manifest__.py
  rental_fees/i18n/fr.po
  rental_fees/models/rental_fees_computation.py
  rental_fees/models/rental_fees_definition.py
  rental_fees/tests/test_rental_fees_computation.py
  rental_fees/views/rental_fees_computation.xml
  setup/commown_contract_forecast/odoo/addons/commown_contract_forecast
  setup/commown_contract_forecast/setup.py
  test-requirements.txt
Labels: bot is merging ⏳, needs review

#227 Add a small check to existing test + a comment
  commown_cooperative_campaign/tests/test_discount.py
Labels: bot is merging ⏳, needs review

#229 Stabilize a test which was crashing at end of month
  rental_fees/tests/test_rental_fees_computation.py
Labels: needs review

#228 Fix redirections to login page by adding website definition in _handle_exception
  commown/models/ir_http.py
  commown/tests/test_ir_http.py
Labels: bot is merging ⏳

#232 Fix another unstable test (see 7e136a2cf296cfe74abf9d7b5d6dd141b963a541)
  commown_contract_forecast/tests/test_contract_line.py
Labels: needs review

#233 Handle payment issues automatically when related invoice payment method is electronic in
  payment_slimpay_issue/models/project_task.py
Labels: bot is merging ⏳, needs review
