Repository commown/commown-odoo-addons, pull requests merged in 2023-02, with the labels that each got.

#135 12.0 imp custom report german t10n for sale order
  custom_report/__init__.py
  custom_report/i18n/__init__.py
  custom_report/i18n/de.po
  custom_report/i18n/fr.po
  custom_report/i18n/i18n.py
  custom_report/migrations/12.0.1.0.0/openupgrade_analysis.txt
  custom_report/models/__init__.py
  custom_report/models/py3o_report_extender.py
  custom_report/report/account_invoice.odt
  custom_report/report/sale_order.odt
  custom_report/tests/__init__.py
  custom_report/tests/common.py
  custom_report/tests/test_account_invoice_report.py
  custom_report/tests/test_sale_order_report.py
Labels: bot is merging ⏳, needs review

#128 12.0 fix commown_devices Change storable product domain
  commown_devices/models/project_task.py
  commown_devices/tests/test_project_task.py
Labels: bot is merging ⏳

#140 Fix delivery address cannot be submitted on the B2B website
  commown/views/address_template.xml
Labels: needs review

#141 Fix delivery address portal form submission when a B2B partner is abroad
  website_sale_b2b/controllers/main.py
Labels: bot is merging ⏳, needs review

#139 12.0 imp commown self troubleshooting fp4 screen
  commown_self_troubleshooting/__manifest__.py
  commown_self_troubleshooting/controllers/main.py
  commown_self_troubleshooting/data/FP/screen/form.xml
  commown_self_troubleshooting/data/FP/screen/issue_template.xml
  commown_self_troubleshooting/data/FP3/screen/form.xml
  commown_self_troubleshooting/data/FP3/screen/issue_template.xml
  commown_self_troubleshooting/data/FP4/screen/form.xml
  commown_self_troubleshooting/data/FP4/screen/issue_template.xml
  commown_self_troubleshooting/data/FP4/screen/meta_data.py
  commown_self_troubleshooting/static/images/FP3/screen/screen_protection.png
  commown_self_troubleshooting/static/images/FP4/screen/screen_protection.png
  commown_self_troubleshooting/tests/test_res_partner.py
Labels: bot is merging ⏳

#143 Enlarge the qty column of the invoice PDF custom py3o report
  custom_report/report/account_invoice.odt
Labels: bot is merging ⏳, needs review

#145 Fix self troubleshooting form submission systematic crash
  commown_self_troubleshooting/controllers/main.py
Labels: bot is merging ⏳, needs review

#146 12.0 imp website sale coupon display coupons on order
  website_sale_coupon/i18n/fr.po
  website_sale_coupon/models/coupon.py
  website_sale_coupon/models/sale_order.py
  website_sale_coupon/views/backoffice.xml
Labels: bot is merging ⏳, needs review

#147 12.0 fix commown shipping recipient partner
  commown_shipping/models/crm_lead.py
  commown_shipping/models/shipping_mixin.py
  commown_shipping/tests/test_crm_lead.py
Labels: bot is merging ⏳, needs review

#148 Fix incorrect quantity in contract when orphan accessory quantity is > 1
  product_rental/models/sale_order_line.py
  product_rental/tests/common.py
  product_rental/tests/test_sale_order.py
Labels: bot is merging ⏳, needs review

#149 Move partner's receivable account onto its parent if needed
  commown/models/res_partner.py
  commown/models/sale_order.py
  commown/tests/test_res_partner.py
Labels: bot is merging ⏳, needs review

#150 12.0 fix commown self troubleshooting contract check permission issue
  commown_self_troubleshooting/controllers/main.py
  project_issue_last_partner_msg_date/models/project_task.py
Labels: bot is merging ⏳, needs review

#151 12.0 imp commown add link to product page on option pages
  commown/i18n/fr.po
  commown/views/website_sale_templates.xml
Labels: bot is merging ⏳, needs review

#152 12.0 imp commown add total amount on portal invoices page
  commown/i18n/de.po
  commown/i18n/fr.po
  commown/views/website_portal_templates.xml
Labels: bot is merging ⏳, needs review

#144 Make sure a risk analysis lead is generated for each product with a followup team
  commown_lead_risk_analysis/models/sale_order.py
  commown_lead_risk_analysis/tests/test_sale_order.py
Labels: bot is merging ⏳, needs review
