Repository commown/commown-odoo-addons, pull requests merged in 2024-09, with the labels that each got.

#315 Fix the invoice merge preferences action on new token signature
  commown/models/payment_token_obsolescence_action.py
  commown/tests/test_payment_token.py
  test-requirements.txt
Labels: bot is merging ⏳, needs review

#270 12.0 imp commown switch sms provider
  commown/__manifest__.py
  commown/models/crm_lead.py
  commown/models/project_task.py
  commown/tests/test_crm_lead.py
  commown/tests/test_project_task.py
  commown/views/actions_crm_lead.xml
  commown_payment_slimpay_issue/__init__.py
  commown_payment_slimpay_issue/__manifest__.py
  commown_payment_slimpay_issue/data/action.xml
  commown_payment_slimpay_issue/data/mail_template.xml
  commown_payment_slimpay_issue/data/project.xml
  commown_payment_slimpay_issue/migrations/12.0.1.0.0/openupgrade_analysis.txt
  commown_payment_slimpay_issue/static/description/icon.png
  commown_payment_slimpay_issue/tests/__init__.py
  commown_payment_slimpay_issue/tests/test_project_task.py
  commown_res_partner_sms/__init__.py
  commown_res_partner_sms/__manifest__.py
  commown_res_partner_sms/data/iap_account.xml
  commown_res_partner_sms/i18n/fr.po
  commown_res_partner_sms/models/__init__.py
  commown_res_partner_sms/models/common.py
  commown_res_partner_sms/models/mail_thread.py
  commown_res_partner_sms/models/res_partner.py
  commown_res_partner_sms/readme/CONTRIBUTORS.rst
  commown_res_partner_sms/readme/CREDITS.rst
  commown_res_partner_sms/readme/DESCRIPTION.rst
  commown_res_partner_sms/tests/__init__.py
  commown_res_partner_sms/tests/models.py
  commown_res_partner_sms/tests/test_common.py
  commown_res_partner_sms/tests/test_mail_thread.py
  commown_res_partner_sms/tests/test_res_partner.py
  commown_shipping/__manifest__.py
  commown_shipping/models/colissimo_utils.py
  payment_slimpay_issue/__manifest__.py
  payment_slimpay_issue/data/action.xml
  payment_slimpay_issue/data/mail_template.xml
  payment_slimpay_issue/i18n/fr.po
  payment_slimpay_issue/models/project_task.py
  payment_slimpay_issue/tests/test_project_task.py
  setup/commown_payment_slimpay_issue/odoo/addons/commown_payment_slimpay_issue
  setup/commown_res_partner_sms/odoo/addons/commown_res_partner_sms
  setup/commown_res_partner_sms/setup.py
  test-requirements.txt
Labels: bot is merging ⏳

#317 Re-introduce a field that count the nubmer of lot on a contract.
  commown_devices/i18n/fr.po
  commown_devices/models/contract.py
  commown_devices/tests/test_contract.py
  commown_devices/views/contract.xml
Labels: merged 🎉

#318 Render the template before converting the html
  commown/models/crm_lead.py
  commown/models/project_task.py
  commown/tests/test_crm_lead.py
  commown/tests/test_project_task.py
  commown_res_partner_sms/models/common.py
  commown_res_partner_sms/models/mail_thread.py
  commown_res_partner_sms/tests/test_common.py
  commown_res_partner_sms/tests/test_mail_thread.py
  commown_shipping/models/colissimo_utils.py
  payment_slimpay_issue/models/project_task.py
  payment_slimpay_issue/tests/test_project_task.py
Labels: bot is merging ⏳

#320 Fix invalid ir.rule domain expression for project task
  customer_manager_base/security/rules.xml
Labels: bot is merging ⏳, needs review

#312 Check we have a contract before trying to display a price on quote portal page
  commown/views/website_sale_templates.xml
Labels: bot is merging ⏳, needs review

#323 Limit Slimpay automatic imports to the end of the fiscal year
  slimpay_statements_autoimport/models/statement_import.py
  slimpay_statements_autoimport/tests/test_statement_import.py
Labels: bot is merging ⏳, needs review

#324 [security] Do not perform important actions as someone else
  urban_mine/models/project_task.py
Labels: bot is merging ⏳, needs review
