Repository commown/commown-odoo-addons, pull requests merged in 2024-12, with the labels that each got.

#338 12.0 fix urban mine missing parcel type
  commown_shipping/__manifest__.py
  commown_shipping/demo/mail_template.xml
  commown_shipping/demo/parcel_type.xml
  urban_mine/__manifest__.py
  urban_mine/data/actions.xml
  urban_mine/data/parcel_type.xml
Labels: needs review

#340 Robustify tests
  rental_fees/tests/test_rental_fees_computation.py
Labels: bot is merging ⏳

#335 Make it possible for customers to manage their company's users
  commown/__manifest__.py
  commown/models/__init__.py
  commown/models/res_partner.py
  commown/models/wizard_portal_access.py
  commown/static/src/xml/menu.xml
  commown/tests/__init__.py
  commown/tests/test_wizard_portal_access.py
  commown/views/website_portal_templates.xml
  customer_team_manager/README.rst
  customer_team_manager/__init__.py
  customer_team_manager/__manifest__.py
  customer_team_manager/data/customer_roles.xml
  customer_team_manager/i18n/customer_team_manager.pot
  customer_team_manager/i18n/de.po
  customer_team_manager/i18n/fr.po
  customer_team_manager/models/__init__.py
  customer_team_manager/models/customer_role.py
  customer_team_manager/models/ir_http.py
  customer_team_manager/models/res_partner.py
  customer_team_manager/models/res_users.py
  customer_team_manager/models/team.py
  customer_team_manager/models/wizard_portal_access.py
  customer_team_manager/readme/CONFIGURE.rst
  customer_team_manager/readme/CONTRIBUTORS.rst
  customer_team_manager/readme/DESCRIPTION.rst
  customer_team_manager/readme/USAGE.rst
  customer_team_manager/readme/newsfragments/.gitkeep
  customer_team_manager/security/groups.xml
  customer_team_manager/security/ir.model.access.csv
  customer_team_manager/security/rules.xml
  customer_team_manager/static/description/icon.png
  customer_team_manager/static/description/index.html
  customer_team_manager/static/src/css/export.css
  customer_team_manager/static/src/js/data_export.js
  customer_team_manager/static/src/js/field_widget.js
  customer_team_manager/static/src/scss/field_widget.scss
  customer_team_manager/static/src/xml/field_widget_template.xml
  customer_team_manager/static/xls/Commown_User_Import_Model.xlsx
  customer_team_manager/tests/__init__.py
  customer_team_manager/tests/common.py
  customer_team_manager/tests/data/import.csv
  customer_team_manager/tests/data/import_error.csv
  customer_team_manager/tests/test_customer_role.py
  customer_team_manager/tests/test_ir_http.py
  customer_team_manager/tests/test_res_partner.py
  customer_team_manager/tests/test_team.py
  customer_team_manager/tests/test_wizard_portal_access.py
  customer_team_manager/views/assets.xml
  customer_team_manager/views/customer_team_manager.xml
  customer_team_manager/views/portal_templates.xml
  customer_team_manager/views/wizard_portal_access.xml
  payment_slimpay_issue/i18n/fr.po
  setup/customer_team_manager/odoo/addons/customer_team_manager
  setup/customer_team_manager/setup.py
  website_sale_b2b/models/res_users.py
  website_sale_b2b/tests/test_payment_portal_templates.py
  website_sale_b2b/tests/test_res_users.py
Labels: bot is merging ⏳, needs review

#341 Fix crash in /shop/submit_order controller when order requires commer…
  website_sale_b2b/tests/test_payment_portal_templates.py
  website_sale_b2b/views/payment_portal_templates.xml
Labels: bot is merging ⏳
