Repository commown/commown-odoo-addons, pull requests merged in 2024-04, with the labels that each got.

#272 12.0 imp rental fees improve error logging
  rental_fees/models/rental_fees_computation.py
Labels: bot is merging ⏳, needs review

#273 Improve fees computation comparison action
  rental_fees/models/rental_fees_computation.py
  rental_fees/tests/test_rental_fees_computation.py
  rental_fees/views/rental_fees_computation.xml
Labels: bot is merging ⏳, needs review

#275 Fix contract_template_line_id domain in contract line edition view
  contract_variable_discount/views/contract.xml
  product_rental/models/contract.py
Labels: bot is merging ⏳, needs review

#277 Create a module for commown accounting and add a view for loan lines
  commown_accounting/__init__.py
  commown_accounting/__manifest__.py
  commown_accounting/i18n/fr.po
  commown_accounting/models/__init__.py
  commown_accounting/models/account_loan_line.py
  commown_accounting/views/account_loan_line.xml
  setup/commown_accounting/odoo/addons/commown_accounting
  setup/commown_accounting/setup.py
Labels: bot is merging ⏳

#271 12.0 imp commown contract forecast account for coop campaigns
  commown_contract_forecast/__manifest__.py
  commown_contract_forecast/data/cron.xml
  commown_contract_forecast/models/contract_line.py
  commown_contract_forecast/tests/test_contract_line.py
  commown_cooperative_campaign/models/contract.py
  commown_cooperative_campaign/models/discount.py
  commown_cooperative_campaign/tests/common.py
  commown_cooperative_campaign/tests/test_discount.py
  contract_variable_discount/models/__init__.py
  contract_variable_discount/models/account_invoice_line.py
  contract_variable_discount/models/contract.py
  contract_variable_discount/models/discount.py
  contract_variable_discount/tests/test_contract.py
Labels: bot is merging ⏳, needs review

#201 12.0 add commown self troubleshooting theft and loss
  commown_self_troubleshooting/__manifest__.py
  commown_self_troubleshooting/controllers/main.py
  commown_self_troubleshooting/data/Assistance/Generic_Issue/form.xml
  commown_self_troubleshooting/data/Assistance/Serenity/form.xml
  commown_self_troubleshooting/data/ContractManagement/termination/form.xml
  commown_self_troubleshooting/data/ContractManagement/theftandloss/form.xml
  commown_self_troubleshooting/data/ContractManagement/theftandloss/issue_template.xml
  commown_self_troubleshooting/data/FP2/battery/form.xml
  commown_self_troubleshooting/data/FP2/camera/form.xml
  commown_self_troubleshooting/data/FP2/micro/form.xml
  commown_self_troubleshooting/data/FP3/display/form.xml
  commown_self_troubleshooting/data/Other/other/form.xml
  commown_self_troubleshooting/data/Smartphone/screen/form.xml
  commown_self_troubleshooting/data/common_steps.xml
  commown_self_troubleshooting/data/troubleshooting.xml
  commown_self_troubleshooting/models/contract.py
  commown_self_troubleshooting/static/src/self_troubleshooting_tour.js
  commown_self_troubleshooting/tests/test_res_partner.py
  commown_self_troubleshooting/tests/test_tour.py
  product_rental/__manifest__.py
  product_rental/data/mail_templates.xml
  product_rental/data/project.xml
Labels: bot is merging ⏳

#280 Make git ignore pytest related files
  .gitignore
Labels: needs review

#274 12.0 imp commown shipping add expedition ref normalization and checks
  commown_shipping/i18n/fr.po
  commown_shipping/models/crm_lead.py
  commown_shipping/models/delivery_mixin.py
  commown_shipping/tests/test_crm_lead.py
Labels: bot is merging ⏳

#283 Fix an error that permitted to select a reserved product in a picking
  commown_devices/models/wizard_project_task_picking.py
  commown_devices/tests/test_project_task.py
Labels: bot is merging ⏳

#284 We were'nt checking if expedition_ref was filled before normalizing
  commown_shipping/models/delivery_mixin.py
Labels: bot is merging ⏳

#282 Create server environement file and add css style depending on enviro…
  server_environment_files/__init__.py
  server_environment_files/__manifest__.py
  server_environment_files/controllers/__init__.py
  server_environment_files/controllers/main.py
  server_environment_files/dev/base.conf
  server_environment_files/production/base.conf
  server_environment_files/static/dev/assets_common.css
  server_environment_files/static/dev/web_login.css
  server_environment_files/static/test/assets_common.css
  server_environment_files/static/test/web_login.css
  server_environment_files/test/base.conf
  server_environment_files/views/template.xml
  setup/server_environment_files/odoo/addons/server_environment_files
  setup/server_environment_files/setup.py
Labels: bot is merging ⏳
