Repository commown/commown-odoo-addons, pull requests merged in 2025-03, with the labels that each got.

#360 16.0 mig commown grade
  .github/workflows/pre-commit.yml
  .github/workflows/test.yml
  .gitignore
  README.rst
  commown_grade/README.rst
  commown_grade/__init__.py
  commown_grade/__manifest__.py
  commown_grade/data/grade.xml
  commown_grade/i18n/commown_grade.pot
  commown_grade/i18n/fr.po
  commown_grade/models/__init__.py
  commown_grade/models/grade.py
  commown_grade/models/grade_history_line.py
  commown_grade/models/stock_lot.py
  commown_grade/readme/DESCRIPTION.rst
  commown_grade/security/groups.xml
  commown_grade/security/ir.model.access.csv
  commown_grade/tests/__init__.py
  commown_grade/tests/test_stock_lot.py
  commown_grade/views/grade.xml
  commown_grade/views/grade_history_line.xml
  commown_grade/views/stock_lot.xml
  readme/DESCRIPTION.rst
  setup/.setuptools-odoo-make-default-ignore
  setup/README
  setup/commown_grade/odoo/addons/commown_grade
  setup/commown_grade/setup.py
Labels: bot is merging ⏳

#359 Fix crash on company merge when resulting company has no customer admin
  commown_automated_control/i18n/fr.po
  commown_b2b_mail_channel/i18n/fr.po
  customer_team_manager/i18n/customer_team_manager.pot
  customer_team_manager/i18n/de.po
  customer_team_manager/i18n/fr.po
  customer_team_manager/models/res_partner.py
  customer_team_manager/models/wizard_portal_access.py
  customer_team_manager/tests/common.py
  customer_team_manager/tests/test_wizard_portal_access.py
  customer_team_manager/views/customer_team_manager.xml
  customer_team_manager/views/wizard_portal_access.xml
Labels: needs review

#358 16.0 mig commown shareholder register
  .github/workflows/test.yml
  commown_shareholder_register/README.rst
  commown_shareholder_register/__init__.py
  commown_shareholder_register/__manifest__.py
  commown_shareholder_register/data/shareholder_tags_update.xml
  commown_shareholder_register/i18n/commown_shareholder_register.pot
  commown_shareholder_register/i18n/fr.po
  commown_shareholder_register/models/__init__.py
  commown_shareholder_register/models/res_company.py
  commown_shareholder_register/models/shareholder_category.py
  commown_shareholder_register/models/shareholder_college.py
  commown_shareholder_register/models/shareholder_register.py
  commown_shareholder_register/models/shareholder_tags_update.py
  commown_shareholder_register/readme/DESCRIPTION.rst
  commown_shareholder_register/report/register.ods
  commown_shareholder_register/report/report.xml
  commown_shareholder_register/security/ir.model.access.csv
  commown_shareholder_register/tests/__init__.py
  commown_shareholder_register/tests/test_shareholder_register.py
  commown_shareholder_register/tests/test_shareholder_tags_update.py
  commown_shareholder_register/views/register.xml
  commown_shareholder_register/views/res_company.xml
  commown_shareholder_register/views/shareholder_category.xml
  commown_shareholder_register/views/shareholder_college.xml
  commown_shareholder_register/views/shareholder_tags_update.xml
  setup/commown_shareholder_register/odoo/addons/commown_shareholder_register
  setup/commown_shareholder_register/setup.py
  test-requirements.txt
Labels: bot is merging ⏳

#362 Improve coverage
  commown_shareholder_register/tests/test_shareholder_college.py
Labels: bot is merging ⏳

#365 12.0 imp payment slimpay issue better reject message
  payment_slimpay_issue/i18n/de.po
  payment_slimpay_issue/i18n/fr.po
  payment_slimpay_issue/i18n/payment_slimpay_issue.pot
  payment_slimpay_issue/models/project_task.py
  payment_slimpay_issue/models/utils.py
Labels: bot is merging ⏳, needs review

#364 16.0 mig commown res partner sms
  commown_res_partner_sms/README.rst
  commown_res_partner_sms/__init__.py
  commown_res_partner_sms/__manifest__.py
  commown_res_partner_sms/data/iap_account.xml
  commown_res_partner_sms/i18n/commown_res_partner_sms.pot
  commown_res_partner_sms/i18n/fr.po
  commown_res_partner_sms/models/__init__.py
  commown_res_partner_sms/models/common.py
  commown_res_partner_sms/models/mail_thread.py
  commown_res_partner_sms/models/res_partner.py
  commown_res_partner_sms/readme/CONTRIBUTORS.rst
  commown_res_partner_sms/readme/CREDITS.rst
  commown_res_partner_sms/readme/DESCRIPTION.rst
  commown_res_partner_sms/static/description/index.html
  commown_res_partner_sms/tests/__init__.py
  commown_res_partner_sms/tests/models.py
  commown_res_partner_sms/tests/test_common.py
  commown_res_partner_sms/tests/test_mail_thread.py
  commown_res_partner_sms/tests/test_res_partner.py
  setup/commown_res_partner_sms/odoo/addons/commown_res_partner_sms
  setup/commown_res_partner_sms/setup.py
  test-requirements.txt
Labels: bot is merging ⏳

#366 16.0 mig ir attachment lang
  ir_attachment_lang/README.rst
  ir_attachment_lang/__init__.py
  ir_attachment_lang/__manifest__.py
  ir_attachment_lang/models/__init__.py
  ir_attachment_lang/models/ir_attachment.py
  ir_attachment_lang/views/ir_attachment.xml
  setup/ir_attachment_lang/odoo/addons/ir_attachment_lang
  setup/ir_attachment_lang/setup.py
Labels: bot is merging ⏳

#368 12.0-imp-commown_self_troubleshooting-screwdriver_text_in_task_template
  commown_self_troubleshooting/data/FP2/camera/issue_template.xml
  commown_self_troubleshooting/data/FP2/micro/issue_template.xml
  commown_self_troubleshooting/data/FP3/display/issue_template.xml
  commown_self_troubleshooting/data/Smartphone/screen/issue_template.xml
  commown_self_troubleshooting/i18n/commown_self_troubleshooting.pot
  commown_self_troubleshooting/i18n/de.po
  commown_self_troubleshooting/i18n/fr.po
  commown_self_troubleshooting/static/src/self_troubleshooting_tour.js
Labels: bot is merging ⏳
