Repository commown/commown-odoo-addons, pull requests merged in 2025-04, with the labels that each got.

#369 12.0 fix payment slimpay issue crash with invoice type partners
  payment_slimpay_issue/__manifest__.py
  payment_slimpay_issue/models/project_task.py
  payment_slimpay_issue/tests/test_project_task.py
Labels: merged 🎉, needs review

#374 12.0 imp add tests to account move slimpay import
  account_move_slimpay_import/__manifest__.py
  account_move_slimpay_import/data/account_account.xml
  account_move_slimpay_import/data/account_journal.xml
  account_move_slimpay_import/data/partner.xml
  account_move_slimpay_import/models/account_journal.py
  account_move_slimpay_import/tests/__init__.py
  account_move_slimpay_import/tests/reporting_sample.csv
  account_move_slimpay_import/tests/test_account_journal.py
  commown/data/account_mass_reconcile.xml
  commown/tests/test_simple_reconciliation.py
  slimpay_statements_autoimport/__manifest__.py
  slimpay_statements_autoimport/models/statement_import.py
Labels: bot is merging ⏳

#373 16.0 mig contract_emails
  contract_emails/README.rst
  contract_emails/__init__.py
  contract_emails/__manifest__.py
  contract_emails/data/channel_message_template.xml
  contract_emails/data/cron.xml
  contract_emails/data/mail_channel.xml
  contract_emails/i18n/contract_emails.pot
  contract_emails/i18n/fr.po
  contract_emails/models/__init__.py
  contract_emails/models/contract.py
  contract_emails/security/ir.model.access.csv
  contract_emails/setup/.setuptools-odoo-make-default-ignore
  contract_emails/setup/README
  contract_emails/static/description/icon.png
  contract_emails/tests/__init__.py
  contract_emails/tests/test_contract.py
  contract_emails/views/contract.xml
  setup/contract_emails/odoo/addons/contract_emails
  setup/contract_emails/setup.py
Labels: bot is merging ⏳

#371 16.0 mig commown automated control
  commown_automated_control/README.rst
  commown_automated_control/__init__.py
  commown_automated_control/__manifest__.py
  commown_automated_control/i18n/commown_automated_control.pot
  commown_automated_control/i18n/fr.po
  commown_automated_control/models/__init__.py
  commown_automated_control/models/automated_control.py
  commown_automated_control/models/base_automation.py
  commown_automated_control/security/groups.xml
  commown_automated_control/security/ir.model.access.csv
  commown_automated_control/tests/__init__.py
  commown_automated_control/tests/test_automated_control.py
  commown_automated_control/tests/test_security.py
  commown_automated_control/views/automated_control.xml
  commown_automated_control/views/base_automation.xml
  setup/commown_automated_control/odoo/addons/commown_automated_control
  setup/commown_automated_control/setup.py
Labels: bot is merging ⏳

#377 16.0 mig commown user roles
  commown_user_roles/README.rst
  commown_user_roles/__init__.py
  commown_user_roles/__manifest__.py
  commown_user_roles/data/res_roles.xml
  commown_user_roles/readme/DESCRIPTION.rst
  commown_user_roles/static/description/index.html
  setup/commown_user_roles/odoo/addons/commown_user_roles
  setup/commown_user_roles/setup.py
  test-requirements.txt
Labels: bot is merging ⏳

#378 16.0 mig server environment files
  .gitignore
  server_environment_files/README.rst
  server_environment_files/__init__.py
  server_environment_files/__manifest__.py
  server_environment_files/controllers/__init__.py
  server_environment_files/controllers/main.py
  server_environment_files/dev/base.conf
  server_environment_files/production/base.conf
  server_environment_files/readme/DESCRIPTION.rst
  server_environment_files/static/description/index.html
  server_environment_files/static/dev/assets_common.css
  server_environment_files/static/dev/web_login.css
  server_environment_files/static/production/assets_common.css
  server_environment_files/static/production/web_login.css
  server_environment_files/static/test/assets_common.css
  server_environment_files/static/test/web_login.css
  server_environment_files/test/base.conf
  server_environment_files/views/template.xml
  setup/server_environment_files/odoo/addons/server_environment_files
  setup/server_environment_files/setup.py
Labels: bot is merging ⏳

#379 16.0 mig commown ergonomy asset
  commown_ergonomy_asset/README.rst
  commown_ergonomy_asset/__init__.py
  commown_ergonomy_asset/__manifest__.py
  commown_ergonomy_asset/readme/DESCRIPTION.rst
  commown_ergonomy_asset/static/description/icon.png
  commown_ergonomy_asset/static/description/index.html
  commown_ergonomy_asset/views/account_asset.xml
  setup/commown_ergonomy_asset/odoo/addons/commown_ergonomy_asset
  setup/commown_ergonomy_asset/setup.py
Labels: bot is merging ⏳

#383 16.0 mig scic
  scic/README.rst
  scic/__init__.py
  scic/__manifest__.py
  scic/i18n/de.po
  scic/i18n/fr.po
  scic/i18n/scic.pot
  scic/models/__init__.py
  scic/models/product_template.py
  scic/models/sale_order.py
  scic/readme/DESCRIPTION.rst
  scic/static/description/index.html
  scic/tests/__init__.py
  scic/tests/test_sale_order.py
  scic/views/product_template.xml
  setup/scic/odoo/addons/scic
  setup/scic/setup.py
Labels: bot is merging ⏳

#382 16.0 mig project issue last partner msg date
  project_issue_last_partner_msg_date/README.rst
  project_issue_last_partner_msg_date/__init__.py
  project_issue_last_partner_msg_date/__manifest__.py
  project_issue_last_partner_msg_date/models/__init__.py
  project_issue_last_partner_msg_date/models/project_task.py
  project_issue_last_partner_msg_date/tests/__init__.py
  project_issue_last_partner_msg_date/tests/test_project_task.py
  setup/project_issue_last_partner_msg_date/odoo/addons/project_issue_last_partner_msg_date
  setup/project_issue_last_partner_msg_date/setup.py
Labels: bot is merging ⏳

#385 Fix invoice report is_b2c test
  custom_report/report/account_invoice.odt
Labels: bot is merging ⏳, needs review

#386 16.0 mig commown accounting
  commown_accounting/README.rst
  commown_accounting/__init__.py
  commown_accounting/__manifest__.py
  commown_accounting/i18n/commown_accounting.pot
  commown_accounting/i18n/fr.po
  commown_accounting/models/__init__.py
  commown_accounting/models/account_loan_line.py
  commown_accounting/readme/DESCRIPTION.rst
  commown_accounting/static/description/index.html
  commown_accounting/views/account_loan_line.xml
  setup/commown_accounting/odoo/addons/commown_accounting
  setup/commown_accounting/setup.py
Labels: bot is merging ⏳

#387 16.0 mig crm stage email template
  crm_stage_email_template/README.rst
  crm_stage_email_template/__init__.py
  crm_stage_email_template/__manifest__.py
  crm_stage_email_template/models/__init__.py
  crm_stage_email_template/models/crm_lead.py
  crm_stage_email_template/models/crm_stage.py
  crm_stage_email_template/tests/__init__.py
  crm_stage_email_template/tests/test_crm_stage_email_template.py
  crm_stage_email_template/views/crm_stage.xml
  setup/crm_stage_email_template/odoo/addons/crm_stage_email_template
  setup/crm_stage_email_template/setup.py
Labels: bot is merging ⏳

#389 Do not crash when a device correspond to more than one PO line...
  rental_fees/models/rental_fees_definition.py
Labels: needs review

#370 16.0 mig commown shipping
  commown_shipping/README.rst
  commown_shipping/__init__.py
  commown_shipping/__manifest__.py
  commown_shipping/data/actions.xml
  commown_shipping/data/cron.xml
  commown_shipping/data/mail_template.xml
  commown_shipping/data/queue_job_channel.xml
  commown_shipping/data/queue_job_function_data.xml
  commown_shipping/data/shipping_accounts.xml
  commown_shipping/demo/mail_template.xml
  commown_shipping/demo/parcel_type.xml
  commown_shipping/i18n/commown_shipping.pot
  commown_shipping/i18n/de.po
  commown_shipping/i18n/fr.po
  commown_shipping/models/__init__.py
  commown_shipping/models/colissimo_utils.py
  commown_shipping/models/crm_lead.py
  commown_shipping/models/crm_team.py
  commown_shipping/models/delivery_mixin.py
  commown_shipping/models/parcel.py
  commown_shipping/models/product.py
  commown_shipping/models/project.py
  commown_shipping/models/project_task.py
  commown_shipping/models/res_partner.py
  commown_shipping/models/shipping_account.py
  commown_shipping/models/shipping_mixin.py
  commown_shipping/models/wizard_print_label.py
  commown_shipping/readme/DESCRIPTION.rst
  commown_shipping/security/ir.model.access.csv
  commown_shipping/setup/.setuptools-odoo-make-default-ignore
  commown_shipping/setup/README
  commown_shipping/static/description/icon.png
  commown_shipping/static/description/index.html
  commown_shipping/tests/__init__.py
  commown_shipping/tests/common.py
  commown_shipping/tests/fake_label.pdf
  commown_shipping/tests/test_crm_lead.py
  commown_shipping/tests/test_project_task.py
  commown_shipping/tests/test_res_partner.py
  commown_shipping/views/crm_lead.xml
  commown_shipping/views/crm_team.xml
  commown_shipping/views/parcels.xml
  commown_shipping/views/product.xml
  commown_shipping/views/project_project.xml
  commown_shipping/views/project_task.xml
  commown_shipping/views/wizard_print_label.xml
  requirements.txt
  setup/commown_shipping/odoo/addons/commown_shipping
  setup/commown_shipping/setup.py
  test-requirements.txt
Labels: bot is merging ⏳
