Repository commown/commown-odoo-addons, pull requests merged in 2025-06, with the labels that each got.

#406 Fix Slimpay payment reject reason display
  .github/workflows/pre-commit.yml
  .pre-commit-config.yaml
  commown/tests/test_project_task.py
  commown_b2b_mail_channel/readme/DESCRIPTION.rst
  commown_b2b_mail_channel/tests/test_res_partner.py
  commown_devices/models/wizard_project_task_to_employee.py
  commown_devices/tests/test_stock_move_line.py
  commown_devices/tests/test_stock_scrap.py
  commown_devices/tests/test_wizard_move_line_validation.py
  commown_project/tests/test_project.py
  commown_self_troubleshooting/tests/test_pages.py
  payment_slimpay_issue/models/project_task.py
  payment_slimpay_issue/tests/test_project_task.py
  product_rental/tests/test_sale_order.py
  rental_fees/tests/test_rental_fees_computation.py
  rental_fees/tests/test_rental_fees_definition.py
  setup/commown_b2b_mail_channel/odoo/addons/commown_b2b_mail_channel
Labels: bot is merging ⏳, needs review

#410 16.0 fix ci packaging error
  test-requirements.txt
  website_sale_payment_slimpay/README.rst
  website_sale_payment_slimpay/static/description/index.html
Labels: bot is merging ⏳

#409 16.0 mig commown cooperative campaign
  commown_cooperative_campaign/README.rst
  commown_cooperative_campaign/__init__.py
  commown_cooperative_campaign/__manifest__.py
  commown_cooperative_campaign/data/action_coupon.xml
  commown_cooperative_campaign/data/ir_config_parameter.xml
  commown_cooperative_campaign/data/queue_job_function.xml
  commown_cooperative_campaign/models/__init__.py
  commown_cooperative_campaign/models/contract.py
  commown_cooperative_campaign/models/coupon.py
  commown_cooperative_campaign/models/discount.py
  commown_cooperative_campaign/models/wizard_late_optin.py
  commown_cooperative_campaign/security/ir.model.access.csv
  commown_cooperative_campaign/tests/__init__.py
  commown_cooperative_campaign/tests/common.py
  commown_cooperative_campaign/tests/test_coupon.py
  commown_cooperative_campaign/tests/test_discount.py
  commown_cooperative_campaign/views/coupon.xml
  commown_cooperative_campaign/views/wizard_late_optin.xml
  requirements.txt
  setup/commown_cooperative_campaign/odoo/addons/commown_cooperative_campaign
  setup/commown_cooperative_campaign/setup.py
Labels: bot is merging ⏳

#404 Add an alert on shop pages to "force" users to inform themselves on provided services
  commown/__manifest__.py
  commown/controllers/website_sale.py
  commown/i18n/commown.pot
  commown/i18n/de.po
  commown/i18n/fr.po
  commown/models/website.py
  commown/static/src/css/website_sale.css
  commown/tests/test_customer_portal.py
  commown/views/website.xml
  commown/views/website_sale_templates.xml
Labels: bot is merging ⏳, needs review

#411 16.0 mig custom report
  custom_report/README.rst
  custom_report/__init__.py
  custom_report/__manifest__.py
  custom_report/i18n/__init__.py
  custom_report/i18n/custom_report.pot
  custom_report/i18n/de.po
  custom_report/i18n/fr.po
  custom_report/i18n/i18n.py
  custom_report/models/__init__.py
  custom_report/models/ir_actions_report.py
  custom_report/models/py3o_report_extender.py
  custom_report/readme/DESCRIPTION.rst
  custom_report/report/account_invoice.odt
  custom_report/report/report.xml
  custom_report/report/sale_order.odt
  custom_report/static/description/icon.png
  custom_report/static/description/index.html
  custom_report/tests/__init__.py
  custom_report/tests/common.py
  custom_report/tests/test_account_invoice_report.py
  custom_report/tests/test_sale_order_report.py
  requirements.txt
  setup/custom_report/odoo/addons/custom_report
  setup/custom_report/setup.py
  test-requirements.txt
Labels: bot is merging ⏳

#416 Fix broken shop view
  product_rental/views/website_sale_templates.xml
Labels: bot is merging ⏳, approved
